

use week7;

CREATE TABLE IF NOT EXISTS products(
  id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR (80),
  price DECIMAL (5, 0)
);


CREATE TABLE IF NOT EXISTS users (
  Uid INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Uname VARCHAR(90),
  Upass VARCHAR(100)
);